# Generated by Django 4.1 on 2024-06-22 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Especialidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("especialidade", models.CharField(max_length=100)),
                ("icone", models.ImageField(blank=True, null=True, upload_to="icones")),
            ],
        ),
        migrations.CreateModel(
            name="Pacientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paciente", models.CharField(max_length=150)),
                ("cns", models.CharField(max_length=15)),
                ("mae", models.CharField(max_length=150)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("raca", models.CharField(max_length=15)),
                ("dn", models.DateField()),
                ("tipagem", models.CharField(max_length=15)),
                ("nacionalidade", models.CharField(max_length=30)),
                ("naturalidade", models.CharField(max_length=30)),
                ("cidade", models.CharField(max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Telefones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefone", models.CharField(max_length=15)),
                ("nomecontato", models.CharField(max_length=15)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telefones",
                        to="usuarios.pacientes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Riscos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resultado", models.CharField(max_length=50)),
                ("data", models.DateField()),
                ("obs", models.CharField(max_length=50)),
                ("apto", models.BooleanField()),
                ("uti", models.BooleanField()),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riscos",
                        to="usuarios.pacientes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medicos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricula", models.CharField(max_length=10)),
                ("crm", models.CharField(max_length=10)),
                ("cns", models.CharField(max_length=15)),
                ("celular", models.CharField(default="", max_length=15)),
                ("trak", models.CharField(max_length=256)),
                ("sisreg", models.CharField(max_length=100)),
                ("sisrep", models.CharField(max_length=256)),
                (
                    "especialidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="usuarios.especialidades",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comorbidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comorbidade", models.CharField(max_length=50)),
                ("medicacao", models.CharField(max_length=50)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comorbidades",
                        to="usuarios.pacientes",
                    ),
                ),
            ],
        ),
    ]
